title: Armada References
description: A list of pop culture references in Armada by Ernest Cline
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
siteurl: http://
baseurl:
google_analytics_code: UA-31980509-11
exclude: [bower.json, README.md]
defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: pages
    values:
      layout: default
