title:
description:
markdown: kramdown
highlighter: pygments
permalink: /:categories/:title/
category_dir: category
paginate: 5
siteurl:
baseurl:
disqus_shortname:
google_analytics_code:
google_analytics_url:
exclude: [bower.json, README.md]
lcb: "{"
rcb: "}"
prose:
  media: "assets/uploads"
  siteurl:
defaults:
  - scope:
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      type: pages
    values:
      layout: default
